speech:
  engine: "pyttsx3"  # or "espeak", "festival"
  voice:
    rate: 200        # Words per minute
    volume: 0.9      # 0.0 to 1.0
    voice_id: null   # null for default, or specific voice ID
  
audio:
  device: "default"  # Audio output device
  
api:
  host: "0.0.0.0"
  port: 5001
  
corpus:
  main_api_url: "http://localhost:5000"